# Site settings
title: Ana María Sosa | Web Citizen
email: anamariasosam@gmail.com
description: Aprendí que todo lo que me enseñan lo debo compartir y no hay mejor forma que un blog para hacerlo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anamariasosa.com" # the base hostname & protocol for your site
twitter_username: anamariasosam
github_username:  anamariasosa
avatar: http://anamariasosa.com/img/blog.png
paginate: 3
locale: en_us

fb_admins: https://facebook.com/people/Ana-Mar%C3%ADa-Sosa/1196953549
fb_appid:  187213728280691

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Ana Sosa
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"